<?php
	load_model("connexion");
	load_model("membre");
	load_model("commande");
	load_model("ligneCommande");
	load_model("article");
	load_model("page");
	load_model("connexionCompte");
	load_model("insertProduit");